# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c111923d66fdfb40528960db9fda60552de861ea77767d70f229c9f1427e67191e83883db9f8dd55b63563aafc8974622dc006458bc9262efbb839af747f61d

test:
  secret_key_base: bad1efdb050186d01f530f9638aee318ab01a0d5c93fd25de82ed0d6d35df9394cb925087e9a01a677a6130acc51e8586da2201121d67ef42567d1388d526ad9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
